[package]
name = "braintree-rs-example"
version = "0.1.0"
authors = ["Damien Radtke <damienradtke@gmail.com>"]

[dependencies.braintree]
url = { version = "2.2.2", features = ["serde"] }
path = "../.."
